package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestWorkflow'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestWorkflow")) {
    triggers {
        remove {
            vcs {
                quietPeriodMode = VcsTrigger.QuietPeriodMode.USE_DEFAULT
                triggerRules = "-:.teamcity/**"
                branchFilter = """
                    +:<default>
                    +:next
                    +:master
                    +:pull/*
                """.trimIndent()
            }
        }
        add {
            schedule {
                schedulingPolicy = cron {
                    minutes = "*/30"
                }
                triggerBuild = always()
                withPendingChangesOnly = false
            }
        }
    }

    dependencies {
        expect(RelativeId("E2E")) {
            snapshot {
            }
        }
        update(RelativeId("E2E")) {
            snapshot {
                runOnSameAgent = true
            }
        }

        expect(RelativeId("SmokeTests")) {
            snapshot {
            }
        }
        update(RelativeId("SmokeTests")) {
            snapshot {
                runOnSameAgent = true
            }
        }

        expect(RelativeId("Lint")) {
            snapshot {
            }
        }
        update(RelativeId("Lint")) {
            snapshot {
                runOnSameAgent = true
            }
        }

        expect(RelativeId("Coverage")) {
            snapshot {
            }
        }
        update(RelativeId("Coverage")) {
            snapshot {
                runOnSameAgent = true
            }
        }

    }
}
